# Site
title: Things Happen
description: Stuff worth sharing - or not.
url: https://lionax.github.io/blog
logo: halve.png                                       # Site logo
locale: de_DE

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
#email:             email
#google.plus:        username
twitter:            justwellbrock
#facebook:           username
github:             lionax
stackoverflow:     6420855/justwellbrock   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          justwellbrock
xing:              Alexander_Wellbrock
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              lootmolch
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
codepen:           lionax
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
